---

- name: Ensure ~/.fonts directory exists
  file:
    state: directory
    path: ~/.fonts

- name: Download Meslo font
  get_url:
    url: "{{meslo_zip_url}}"
    dest: "{{meslo_zip_tmp}}"

- name: Unpack Meslo font
  unarchive:
    copy: no
    src: "{{meslo_zip_tmp}}"
    dest: "{{meslo_unzip_tmp}}"

- name: Copy Meslo font to ~/.fonts directory
  copy:
    src: "{{meslo_unzip_tmp}}/Meslo LG v{{meslo_version}}/
